import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useEffect } from 'react'
const Home: NextPage = () => {



  useEffect(() => {
    if (typeof document !== 'undefined') {
      const placeholder = document.querySelector("#thirdPartyContainer")
      if (!placeholder) return;
      placeholder.insertAdjacentHTML("afterbegin", "<div>here is the 3rd party injected stuff</div>")

    }
    return () => {
      // cleanup
    }
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.container}>

        <header className={styles.header}>Header</header>
        <main className={styles.main}>
          <div>Dynamic Page</div>

          <div id="thirdPartyContainer"></div>

        </main>

        <footer className={styles.footer}>
          This is the footer for dynamic page
        </footer>
      </section>
    </>
  )
}

export default Home
