import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>Header</header>
      <main className={styles.main}>
        <div>Dynamic Page</div>
      </main>

      <footer className={styles.footer}>
        This is the footer
      </footer>
    </div>
  )
}

export default Home
